//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Space_Fridge_Forum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fridge
    {
        // 1:1 User
        [Key]
        [ForeignKey("User")]
        public string UserId { get; set; }
        public string Name { get; set; }
        public string HexColor { get; set; }
    
        public virtual ApplicationUser User { get; set; }
        public virtual List<Ingredient> Ingredients { get; set; }
    }
}
