//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Space_Fridge_Forum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public int Id { get; set; }
        public int Value { get; set; }
    
        public virtual IngredientType IngredientType { get; set; }
        public virtual IngredientUnit IngredientUnit { get; set; }
    }
}
