// <auto-generated />
namespace Space_Fridge_Forum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Change_Ingredient_Relationships : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_Ingredient_Relationships));
        
        string IMigrationMetadata.Id
        {
            get { return "201904011410238_Change_Ingredient_Relationships"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
