// <auto-generated />
namespace Space_Fridge_Forum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Misc_Refactor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Misc_Refactor));
        
        string IMigrationMetadata.Id
        {
            get { return "201904011047330_Misc_Refactor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
